import { IFighterProps } from "../entities/fighter/fighter.types";

export const CHARACTERS: IFighterProps[] = [
  { name: "Goku", speed: 90, attack: 95, defense: 85, icon: "🟠" },
  { name: "Vegeta", speed: 88, attack: 92, defense: 82, icon: "🔵" },
  { name: "Gohan", speed: 85, attack: 89, defense: 80, icon: "🟡" },
  { name: "Piccolo", speed: 78, attack: 83, defense: 88, icon: "🟩" },
  { name: "Krillin", speed: 70, attack: 65, defense: 60, icon: "🟤" },
  { name: "Yamcha", speed: 68, attack: 64, defense: 58, icon: "⚫" },
  { name: "Tien", speed: 72, attack: 66, defense: 62, icon: "⚪" },
  { name: "Trunks", speed: 82, attack: 86, defense: 78, icon: "🟣" },
  { name: "Bulma", speed: 60, attack: 30, defense: 50, icon: "👩" },
  { name: "Android 18", speed: 80, attack: 85, defense: 84, icon: "🤖" },
  { name: "Frieza", speed: 84, attack: 90, defense: 80, icon: "🟪" },
  { name: "Cell", speed: 82, attack: 92, defense: 86, icon: "🟢" },
  { name: "Majin Buu", speed: 75, attack: 88, defense: 90, icon: "🟥" },
  { name: "Beerus", speed: 93, attack: 95, defense: 88, icon: "😼" },
  { name: "Whis", speed: 95, attack: 92, defense: 90, icon: "🧙‍♂️" },
  { name: "Jiren", speed: 92, attack: 96, defense: 94, icon: "💪" },
  { name: "Broly", speed: 89, attack: 98, defense: 88, icon: "💥" },
  { name: "Zamasu", speed: 83, attack: 87, defense: 85, icon: "⚔️" },
  { name: "Goku Black", speed: 85, attack: 91, defense: 80, icon: "🖤" },
  { name: "Caulifla", speed: 78, attack: 84, defense: 75, icon: "🌸" },
  { name: "Kale", speed: 76, attack: 86, defense: 88, icon: "🍃" },
  { name: "Cabba", speed: 74, attack: 80, defense: 70, icon: "🟨" },
  { name: "Hit", speed: 90, attack: 88, defense: 85, icon: "🕒" },
  { name: "Toppo", speed: 80, attack: 87, defense: 89, icon: "🔴" },
  { name: "Dabura", speed: 70, attack: 80, defense: 75, icon: "👹" },
  { name: "Android 17", speed: 82, attack: 83, defense: 85, icon: "🤖" },
  { name: "Raditz", speed: 68, attack: 70, defense: 65, icon: "🦁" },
  { name: "Nappa", speed: 60, attack: 75, defense: 70, icon: "🧔" },
  { name: "Videl", speed: 65, attack: 58, defense: 55, icon: "👊" },
  { name: "Pan", speed: 72, attack: 68, defense: 60, icon: "👶" },
  { name: "Goten", speed: 77, attack: 70, defense: 65, icon: "🟠" },
  { name: "Roshi", speed: 60, attack: 55, defense: 50, icon: "👴" },
  { name: "Bardock", speed: 80, attack: 85, defense: 78, icon: "🛡️" },
  { name: "King Vegeta", speed: 75, attack: 80, defense: 77, icon: "👑" },
  { name: "Cooler", speed: 83, attack: 87, defense: 82, icon: "❄️" },
  { name: "Turles", speed: 72, attack: 76, defense: 70, icon: "🍏" },
  { name: "Gotenks", speed: 85, attack: 88, defense: 80, icon: "🎃" },
  { name: "Gogeta", speed: 92, attack: 95, defense: 88, icon: "🔥" },
  { name: "Vegito", speed: 93, attack: 96, defense: 89, icon: "⚡" },
  { name: "Supreme Kai", speed: 70, attack: 72, defense: 65, icon: "🟣" },
  { name: "Kibito", speed: 68, attack: 70, defense: 67, icon: "🔴" },
  { name: "Android 16", speed: 65, attack: 78, defense: 80, icon: "🤖" },
  { name: "Great Saiyaman", speed: 76, attack: 70, defense: 72, icon: "🦸" },
  { name: "Majin Vegeta", speed: 88, attack: 94, defense: 84, icon: "😈" },
  { name: "Mr. Satan", speed: 50, attack: 40, defense: 45, icon: "🎤" },
  { name: "Shenron", speed: 60, attack: 85, defense: 95, icon: "🐉" },
  { name: "Porunga", speed: 55, attack: 82, defense: 92, icon: "🐲" },
  { name: "Baby", speed: 80, attack: 85, defense: 82, icon: "🍼" },
  { name: "Super Buu", speed: 77, attack: 89, defense: 88, icon: "🍫" },
  { name: "Pikkon", speed: 84, attack: 83, defense: 79, icon: "🥋" },
  { name: "Dr. Gero", speed: 60, attack: 65, defense: 70, icon: "🧪" },
  { name: "Zarbon", speed: 74, attack: 75, defense: 68, icon: "💎" },
  { name: "Dodoria", speed: 65, attack: 70, defense: 66, icon: "💪" },
  { name: "Recoome", speed: 68, attack: 80, defense: 70, icon: "👊" },
  { name: "Burter", speed: 92, attack: 74, defense: 68, icon: "💨" },
  { name: "Jeice", speed: 75, attack: 76, defense: 72, icon: "🟠" },
  { name: "Guldo", speed: 50, attack: 55, defense: 60, icon: "⏳" },
  { name: "Nail", speed: 68, attack: 75, defense: 72, icon: "💚" },
  { name: "Frost", speed: 80, attack: 85, defense: 82, icon: "❄️" },
  { name: "Champa", speed: 78, attack: 86, defense: 83, icon: "🍖" },
  { name: "Moro", speed: 83, attack: 90, defense: 85, icon: "🐐" },
  { name: "Kefla", speed: 88, attack: 92, defense: 86, icon: "🌈" },
  { name: "Grand Priest", speed: 95, attack: 98, defense: 97, icon: "👼" },
  { name: "Zeno", speed: 99, attack: 100, defense: 99, icon: "👑" },
];
